# Generated by Django 4.2 on 2025-09-13 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Subjects', '0003_subject_grade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('second_name', models.CharField(max_length=200)),
                ('third_name', models.CharField(blank=True, max_length=200)),
                ('gender', models.CharField(choices=[('Boy', 'Boy'), ('Girl', 'Girl')], max_length=200)),
                ('image', models.ImageField(blank=True, upload_to='students')),
                ('residence', models.CharField(max_length=200)),
                ('favorite_sport', models.CharField(max_length=200)),
                ('grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Subjects.grade')),
            ],
        ),
    ]
