# Generated by Django 4.2 on 2025-09-13 12:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='hobbies',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='favorite_sport',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
