# Generated by Django 4.2 on 2025-07-22 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Assessments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
