# Generated by Django 4.2 on 2025-07-22 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Assessments', '0002_assessment_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentresult',
            name='max_score',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
