# Generated by Django 4.2 on 2025-07-22 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Assessments', '0003_alter_assessmentresult_max_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessmentresult',
            name='max_score',
        ),
    ]
