# Generated by Django 4.2 on 2025-07-22 15:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Assessments', '0004_remove_assessmentresult_max_score'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assessment',
            options={'ordering': ('-created',)},
        ),
        migrations.AddField(
            model_name='assessment',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
