# Generated by Django 4.2 on 2025-07-23 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Assessments', '0005_alter_assessment_options_assessment_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentresult',
            name='answers',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
