# Generated by Django 4.2 on 2025-07-23 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Assessments', '0006_assessmentresult_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='grade',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='grade_assessments', to='Assessments.grade'),
            preserve_default=False,
        ),
    ]
