# Generated by Django 4.2 on 2025-07-23 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Assessments', '0008_alter_assessment_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='grade',
        ),
    ]
