# Generated by Django 4.2 on 2025-07-23 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Assessments', '0009_remove_assessment_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grade_assessments', to='Assessments.grade'),
        ),
    ]
