# Generated by Django 4.2 on 2025-07-23 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Assessments', '0010_assessment_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_assessments', to='Assessments.grade'),
        ),
    ]
