# Generated by Django 4.2 on 2025-07-23 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Subjects', '0002_remove_subject_grade'),
        ('Assessments', '0011_alter_assessment_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_assessments', to='Subjects.grade'),
        ),
        migrations.DeleteModel(
            name='Grade',
        ),
    ]
