# Generated by Django 3.2.5 on 2025-07-25 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Assessments', '0013_assessment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
