# Generated by Django 4.2 on 2025-09-09 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Assessments', '0016_alter_question_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={},
        ),
    ]
