# Generated by Django 4.2 on 2025-09-09 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Assessments', '0017_alter_question_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assessmentresult',
            options={'ordering': ('-total_score',)},
        ),
    ]
