# Generated by Django 4.2 on 2025-08-30 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Strand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('grade', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='SubStrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('strand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substrands', to='ELearning.strand')),
            ],
        ),
        migrations.AddField(
            model_name='strand',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strands', to='ELearning.subject'),
        ),
        migrations.CreateModel(
            name='LearningOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('substrand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outcomes', to='ELearning.substrand')),
            ],
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_type', models.CharField(choices=[('quiz', 'Quiz'), ('project', 'Project'), ('portfolio', 'Portfolio')], max_length=50)),
                ('rubric', models.JSONField(help_text='CBC rubric details')),
                ('outcome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='ELearning.learningoutcome')),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('video', 'Video'), ('quiz', 'Quiz'), ('simulation', 'Simulation'), ('practical', 'Practical'), ('image', 'Image')], max_length=50)),
                ('resource_link', models.URLField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='activities/images/')),
                ('outcome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='ELearning.learningoutcome')),
            ],
        ),
    ]
