# Generated by Django 4.2 on 2025-08-30 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Subjects', '0002_remove_subject_grade'),
        ('ELearning', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grade_subject', to='Subjects.grade'),
        ),
    ]
