# Generated by Django 4.2 on 2025-08-30 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ELearning', '0002_alter_subject_grade'),
    ]

    operations = [
        migrations.CreateModel(
            name='StrandNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('strand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='ELearning.strand')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
