# Generated by Django 4.2 on 2025-08-30 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ELearning', '0003_strandnote'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StrandNote',
            new_name='SubStrandNote',
        ),
    ]
