# Generated by Django 4.2 on 2025-08-31 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ELearning', '0004_rename_strandnote_substrandnote'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('substrand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='ELearning.substrand')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('substrand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='ELearning.substrand')),
            ],
        ),
        migrations.CreateModel(
            name='ImageResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='substrand_images/')),
                ('substrand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='ELearning.substrand')),
            ],
        ),
    ]
