# Generated by Django 4.2 on 2025-09-02 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ELearning', '0005_videoresource_note_imageresource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningoutcome',
            name='substrand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_outcomes', to='ELearning.substrand'),
        ),
    ]
