# Generated by Django 4.2 on 2025-07-23 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Subjects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='grade',
        ),
    ]
