# Generated by Django 5.2.7 on 2025-11-02 04:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '__first__'),
        ('Subjects', '0003_subject_grade'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grade',
            options={'ordering': ('-name',)},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ('numbering',)},
        ),
        migrations.AddField(
            model_name='subject',
            name='numbering',
            field=models.PositiveIntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subject',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_subjects', to='Students.teachers'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='grade',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='grade_subjects', to='Subjects.grade'),
        ),
    ]
